#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 17 15:46:07 -03 2018
# SW Build 2348494 on Mon Oct  1 18:25:39 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim alu2fifo_uut_behav -key {Behavioral:sim_3:Functional:alu2fifo_uut} -tclbatch alu2fifo_uut.tcl -view /media/lu/Data/FACU/ARQUITECTURA/PRACTICOS/2018/TP2/TP2v1/txfifo_behav.wcfg -log simulate.log
